# Server Configuration
server.port=8080

# Database Configuration aiven
spring.datasource.url=jdbc:postgresql://krishi-setu-kellikai-03.a.aivencloud.com:26379/agri?ssl=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_NjGZxgiR-C80S1LGVHD
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000

# Database Configuration railway
#spring.datasource.url=jdbc:postgresql://turntable.proxy.rlwy.net:14182/railway
#spring.datasource.username=postgres
#spring.datasource.password=pihgxrryvIoBrMAuKGaXRnTIhbWXNnoH
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# JWT Configuration
app.jwt.secret=mySecretKeyForJWTTokenGeneration123456789
app.jwt.expiration=86400000
# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
# ImageKit Configuration
imagekit.private-key=private_XWAlG2tcBbAzL4eOSaEGnpWoq14=
imagekit.public-key=public_EWBsC6WnEkPBRFevX+CMxRLvQpI=
imagekit.url-endpoint=https://ik.imagekit.io/agri
# Razorpay Configuration
razorpay.key.id=rzp_live_SO310RmXWIxsEE
razorpay.key.secret=EdHdyojl3oR43msTYOXq614C
# Logging Configuration
logging.level.org.agri.agritrade=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Security Configuration
spring.security.require-ssl=false
# Application Configuration
app.name=krishi-setu
app.version=1.0.0
app.description=Agricultural Trading Platform

